# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1090, 711)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(6, 9, 1071, 641))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 1221, 601))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_Scan = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_Scan.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_Scan.setObjectName("gridLayout_Scan")
        self.groupBox_5 = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_plot = QtWidgets.QWidget(self.groupBox_5)
        self.widget_plot.setObjectName("widget_plot")
        self.verticalLayout.addWidget(self.widget_plot)
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_8.setMaximumSize(QtCore.QSize(16777215, 80))
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.radioButton_Intensity = QtWidgets.QRadioButton(self.groupBox_8)
        self.radioButton_Intensity.setObjectName("radioButton_Intensity")
        self.horizontalLayout_11.addWidget(self.radioButton_Intensity)
        self.radioButton_Absorbance = QtWidgets.QRadioButton(self.groupBox_8)
        self.radioButton_Absorbance.setChecked(True)
        self.radioButton_Absorbance.setObjectName("radioButton_Absorbance")
        self.horizontalLayout_11.addWidget(self.radioButton_Absorbance)
        self.radioButton_Reflectance = QtWidgets.QRadioButton(self.groupBox_8)
        self.radioButton_Reflectance.setObjectName("radioButton_Reflectance")
        self.horizontalLayout_11.addWidget(self.radioButton_Reflectance)
        self.radioButton_Reference = QtWidgets.QRadioButton(self.groupBox_8)
        self.radioButton_Reference.setObjectName("radioButton_Reference")
        self.horizontalLayout_11.addWidget(self.radioButton_Reference)
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.verticalLayout.addWidget(self.groupBox_8)
        self.gridLayout_Scan.addWidget(self.groupBox_5, 0, 1, 1, 1)
        self.tabWidget_ScanSetting = QtWidgets.QTabWidget(self.layoutWidget)
        self.tabWidget_ScanSetting.setMaximumSize(QtCore.QSize(350, 16777215))
        self.tabWidget_ScanSetting.setObjectName("tabWidget_ScanSetting")
        self.tab_6 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tab_6.sizePolicy().hasHeightForWidth())
        self.tab_6.setSizePolicy(sizePolicy)
        self.tab_6.setMinimumSize(QtCore.QSize(325, 545))
        self.tab_6.setObjectName("tab_6")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.tab_6)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.verticalLayout_40 = QtWidgets.QVBoxLayout()
        self.verticalLayout_40.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_40.setSpacing(2)
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.groupBox_scan_controls_2 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_scan_controls_2.setObjectName("groupBox_scan_controls_2")
        self.gridLayout_36 = QtWidgets.QGridLayout(self.groupBox_scan_controls_2)
        self.gridLayout_36.setContentsMargins(-1, 6, -1, 6)
        self.gridLayout_36.setVerticalSpacing(2)
        self.gridLayout_36.setObjectName("gridLayout_36")
        self.pushButton_edit_scan_config_2 = QtWidgets.QPushButton(self.groupBox_scan_controls_2)
        self.pushButton_edit_scan_config_2.setObjectName("pushButton_edit_scan_config_2")
        self.gridLayout_36.addWidget(self.pushButton_edit_scan_config_2, 0, 2, 1, 1)
        self.label_scan_time_2 = QtWidgets.QLabel(self.groupBox_scan_controls_2)
        self.label_scan_time_2.setObjectName("label_scan_time_2")
        self.gridLayout_36.addWidget(self.label_scan_time_2, 3, 0, 1, 1)
        self.label_num_repeat_4 = QtWidgets.QLabel(self.groupBox_scan_controls_2)
        self.label_num_repeat_4.setObjectName("label_num_repeat_4")
        self.gridLayout_36.addWidget(self.label_num_repeat_4, 2, 0, 1, 1)
        self.comboBox_scanID = QtWidgets.QComboBox(self.groupBox_scan_controls_2)
        self.comboBox_scanID.setObjectName("comboBox_scanID")
        self.gridLayout_36.addWidget(self.comboBox_scanID, 0, 0, 1, 2)
        self.label_scan_time_val = QtWidgets.QLabel(self.groupBox_scan_controls_2)
        self.label_scan_time_val.setText("")
        self.label_scan_time_val.setObjectName("label_scan_time_val")
        self.gridLayout_36.addWidget(self.label_scan_time_val, 3, 1, 1, 2)
        self.spinBox_numRepeat = QtWidgets.QSpinBox(self.groupBox_scan_controls_2)
        self.spinBox_numRepeat.setMinimum(1)
        self.spinBox_numRepeat.setObjectName("spinBox_numRepeat")
        self.gridLayout_36.addWidget(self.spinBox_numRepeat, 2, 1, 1, 2)
        self.verticalLayout_40.addWidget(self.groupBox_scan_controls_2)
        self.groupBox_ref_controls_2 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_ref_controls_2.setObjectName("groupBox_ref_controls_2")
        self.gridLayout_37 = QtWidgets.QGridLayout(self.groupBox_ref_controls_2)
        self.gridLayout_37.setContentsMargins(-1, 6, -1, 6)
        self.gridLayout_37.setVerticalSpacing(2)
        self.gridLayout_37.setObjectName("gridLayout_37")
        self.radioButton_ref_factory = QtWidgets.QRadioButton(self.groupBox_ref_controls_2)
        self.radioButton_ref_factory.setChecked(True)
        self.radioButton_ref_factory.setObjectName("radioButton_ref_factory")
        self.gridLayout_37.addWidget(self.radioButton_ref_factory, 0, 0, 1, 1)
        self.radioButton_ref_prev = QtWidgets.QRadioButton(self.groupBox_ref_controls_2)
        self.radioButton_ref_prev.setObjectName("radioButton_ref_prev")
        self.gridLayout_37.addWidget(self.radioButton_ref_prev, 0, 1, 1, 1)
        self.radioButton_ref_new = QtWidgets.QRadioButton(self.groupBox_ref_controls_2)
        self.radioButton_ref_new.setObjectName("radioButton_ref_new")
        self.gridLayout_37.addWidget(self.radioButton_ref_new, 0, 2, 1, 1)
        self.label_ref_timestamp_2 = QtWidgets.QLabel(self.groupBox_ref_controls_2)
        self.label_ref_timestamp_2.setText("")
        self.label_ref_timestamp_2.setObjectName("label_ref_timestamp_2")
        self.gridLayout_37.addWidget(self.label_ref_timestamp_2, 1, 0, 1, 3)
        self.verticalLayout_40.addWidget(self.groupBox_ref_controls_2)
        self.groupBox_lampControl = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_lampControl.setObjectName("groupBox_lampControl")
        self.gridLayout_38 = QtWidgets.QGridLayout(self.groupBox_lampControl)
        self.gridLayout_38.setContentsMargins(-1, 6, -1, 6)
        self.gridLayout_38.setVerticalSpacing(2)
        self.gridLayout_38.setObjectName("gridLayout_38")
        self.lineEdit_lamp_stable_time = QtWidgets.QLineEdit(self.groupBox_lampControl)
        self.lineEdit_lamp_stable_time.setEnabled(True)
        self.lineEdit_lamp_stable_time.setCursorPosition(3)
        self.lineEdit_lamp_stable_time.setDragEnabled(False)
        self.lineEdit_lamp_stable_time.setReadOnly(False)
        self.lineEdit_lamp_stable_time.setClearButtonEnabled(False)
        self.lineEdit_lamp_stable_time.setObjectName("lineEdit_lamp_stable_time")
        self.gridLayout_38.addWidget(self.lineEdit_lamp_stable_time, 1, 2, 1, 1)
        self.radioButton_always_off = QtWidgets.QRadioButton(self.groupBox_lampControl)
        self.radioButton_always_off.setObjectName("radioButton_always_off")
        self.gridLayout_38.addWidget(self.radioButton_always_off, 0, 1, 1, 1)
        self.radioButton_always_on = QtWidgets.QRadioButton(self.groupBox_lampControl)
        self.radioButton_always_on.setObjectName("radioButton_always_on")
        self.gridLayout_38.addWidget(self.radioButton_always_on, 0, 0, 1, 1)
        self.radioButton_Lamp_Stable_Time = QtWidgets.QRadioButton(self.groupBox_lampControl)
        self.radioButton_Lamp_Stable_Time.setChecked(True)
        self.radioButton_Lamp_Stable_Time.setObjectName("radioButton_Lamp_Stable_Time")
        self.gridLayout_38.addWidget(self.radioButton_Lamp_Stable_Time, 1, 0, 1, 2)
        self.verticalLayout_40.addWidget(self.groupBox_lampControl)
        self.gridLayout_21 = QtWidgets.QGridLayout()
        self.gridLayout_21.setContentsMargins(10, -1, 10, -1)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.label_pga_gain_2 = QtWidgets.QLabel(self.tab_6)
        self.label_pga_gain_2.setObjectName("label_pga_gain_2")
        self.gridLayout_21.addWidget(self.label_pga_gain_2, 0, 0, 1, 1)
        self.comboBox_pga_gain = QtWidgets.QComboBox(self.tab_6)
        self.comboBox_pga_gain.setCurrentText("Auto")
        self.comboBox_pga_gain.setObjectName("comboBox_pga_gain")
        self.comboBox_pga_gain.addItem("")
        self.comboBox_pga_gain.addItem("")
        self.comboBox_pga_gain.setItemText(1, "64")
        self.comboBox_pga_gain.addItem("")
        self.comboBox_pga_gain.setItemText(2, "32")
        self.comboBox_pga_gain.addItem("")
        self.comboBox_pga_gain.setItemText(3, "16")
        self.comboBox_pga_gain.addItem("")
        self.comboBox_pga_gain.setItemText(4, "8")
        self.comboBox_pga_gain.addItem("")
        self.comboBox_pga_gain.setItemText(5, "4")
        self.comboBox_pga_gain.addItem("")
        self.comboBox_pga_gain.setItemText(6, "2")
        self.comboBox_pga_gain.addItem("")
        self.comboBox_pga_gain.setItemText(7, "1")
        self.gridLayout_21.addWidget(self.comboBox_pga_gain, 0, 1, 1, 1)
        self.verticalLayout_40.addLayout(self.gridLayout_21)
        self.pushButton_scan = QtWidgets.QPushButton(self.tab_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_scan.sizePolicy().hasHeightForWidth())
        self.pushButton_scan.setSizePolicy(sizePolicy)
        self.pushButton_scan.setMinimumSize(QtCore.QSize(289, 40))
        self.pushButton_scan.setCheckable(False)
        self.pushButton_scan.setObjectName("pushButton_scan")
        self.verticalLayout_40.addWidget(self.pushButton_scan)
        self.gridLayout_56 = QtWidgets.QGridLayout()
        self.gridLayout_56.setObjectName("gridLayout_56")
        self.checkBox_GlitchFilter = QtWidgets.QCheckBox(self.tab_6)
        self.checkBox_GlitchFilter.setEnabled(False)
        self.checkBox_GlitchFilter.setObjectName("checkBox_GlitchFilter")
        self.gridLayout_56.addWidget(self.checkBox_GlitchFilter, 0, 0, 1, 1)
        self.checkBox_SaveBlackLevel = QtWidgets.QCheckBox(self.tab_6)
        self.checkBox_SaveBlackLevel.setObjectName("checkBox_SaveBlackLevel")
        self.gridLayout_56.addWidget(self.checkBox_SaveBlackLevel, 0, 1, 1, 1)
        self.ckb_saveRawADC = QtWidgets.QCheckBox(self.tab_6)
        self.ckb_saveRawADC.setObjectName("ckb_saveRawADC")
        self.gridLayout_56.addWidget(self.ckb_saveRawADC, 0, 2, 1, 1)
        self.verticalLayout_40.addLayout(self.gridLayout_56)
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setObjectName("gridLayout_18")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_18.addItem(spacerItem1, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_18.addItem(spacerItem2, 3, 2, 1, 1)
        self.label_connected = QtWidgets.QLabel(self.tab_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_connected.sizePolicy().hasHeightForWidth())
        self.label_connected.setSizePolicy(sizePolicy)
        self.label_connected.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(16)
        self.label_connected.setFont(font)
        self.label_connected.setObjectName("label_connected")
        self.gridLayout_18.addWidget(self.label_connected, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_18.addItem(spacerItem3, 2, 2, 1, 1)
        self.verticalLayout_40.addLayout(self.gridLayout_18)
        self.horizontalLayout_21.addLayout(self.verticalLayout_40)
        self.tabWidget_ScanSetting.addTab(self.tab_6, "")
        self.gridLayout_Scan.addWidget(self.tabWidget_ScanSetting, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.widget_3 = QtWidgets.QWidget(self.groupBox_3)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pushButton_ResetSys = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_ResetSys.setObjectName("pushButton_ResetSys")
        self.gridLayout_6.addWidget(self.pushButton_ResetSys, 1, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.widget_3)
        self.label_35.setObjectName("label_35")
        self.gridLayout_6.addWidget(self.label_35, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.widget_3, 0, 1, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.groupBox_3)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_31 = QtWidgets.QLabel(self.widget_4)
        self.label_31.setObjectName("label_31")
        self.gridLayout_5.addWidget(self.label_31, 1, 0, 1, 1)
        self.pushButton_ReplaceRef = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_ReplaceRef.setObjectName("pushButton_ReplaceRef")
        self.gridLayout_5.addWidget(self.pushButton_ReplaceRef, 3, 0, 1, 1)
        self.gridLayout_12.addWidget(self.widget_4, 1, 1, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.groupBox_3)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_ResotreRef = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_ResotreRef.setObjectName("pushButton_ResotreRef")
        self.gridLayout_3.addWidget(self.pushButton_ResotreRef, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.widget_2, 1, 2, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.groupBox_3)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label = QtWidgets.QLabel(self.widget_5)
        self.label.setObjectName("label")
        self.gridLayout_11.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton_BackUpRef = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_BackUpRef.setObjectName("pushButton_BackUpRef")
        self.gridLayout_11.addWidget(self.pushButton_BackUpRef, 1, 0, 1, 1)
        self.gridLayout_12.addWidget(self.widget_5, 0, 2, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_3, 0, 2, 2, 3)
        self.groupBox_datetime = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_datetime.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_datetime.setObjectName("groupBox_datetime")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_datetime)
        self.gridLayout_7.setContentsMargins(-1, 6, -1, 6)
        self.gridLayout_7.setVerticalSpacing(4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lineEdit_DateTime_utl = QtWidgets.QLineEdit(self.groupBox_datetime)
        self.lineEdit_DateTime_utl.setObjectName("lineEdit_DateTime_utl")
        self.gridLayout_7.addWidget(self.lineEdit_DateTime_utl, 0, 0, 1, 2)
        self.pushButton_GetDateTime = QtWidgets.QPushButton(self.groupBox_datetime)
        self.pushButton_GetDateTime.setObjectName("pushButton_GetDateTime")
        self.gridLayout_7.addWidget(self.pushButton_GetDateTime, 1, 1, 1, 1)
        self.pushButton_SyncDateTime = QtWidgets.QPushButton(self.groupBox_datetime)
        self.pushButton_SyncDateTime.setObjectName("pushButton_SyncDateTime")
        self.gridLayout_7.addWidget(self.pushButton_SyncDateTime, 1, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_datetime, 1, 0, 1, 1)
        self.groupBox_device_info = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_device_info.setObjectName("groupBox_device_info")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.groupBox_device_info)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_9 = QtWidgets.QLabel(self.groupBox_device_info)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_device_DLPCver = QtWidgets.QLabel(self.groupBox_device_info)
        self.label_device_DLPCver.setText("")
        self.label_device_DLPCver.setObjectName("label_device_DLPCver")
        self.gridLayout_2.addWidget(self.label_device_DLPCver, 2, 1, 1, 1)
        self.label_device_UUID = QtWidgets.QLabel(self.groupBox_device_info)
        self.label_device_UUID.setText("")
        self.label_device_UUID.setObjectName("label_device_UUID")
        self.gridLayout_2.addWidget(self.label_device_UUID, 9, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_device_info)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_device_GUIver = QtWidgets.QLabel(self.groupBox_device_info)
        self.label_device_GUIver.setText("")
        self.label_device_GUIver.setObjectName("label_device_GUIver")
        self.gridLayout_2.addWidget(self.label_device_GUIver, 0, 1, 1, 1)
        self.label_device_LampUsage = QtWidgets.QLabel(self.groupBox_device_info)
        self.label_device_LampUsage.setText("")
        self.label_device_LampUsage.setObjectName("label_device_LampUsage")
        self.gridLayout_2.addWidget(self.label_device_LampUsage, 10, 1, 1, 1)
        self.label_device_TivaSWver = QtWidgets.QLabel(self.groupBox_device_info)
        self.label_device_TivaSWver.setText("")
        self.label_device_TivaSWver.setObjectName("label_device_TivaSWver")
        self.gridLayout_2.addWidget(self.label_device_TivaSWver, 1, 1, 1, 1)
        self.label_device_SpectrumLibVer = QtWidgets.QLabel(self.groupBox_device_info)
        self.label_device_SpectrumLibVer.setText("")
        self.label_device_SpectrumLibVer.setObjectName("label_device_SpectrumLibVer")
        self.gridLayout_2.addWidget(self.label_device_SpectrumLibVer, 3, 1, 1, 1)
        self.label_device_ManufSer = QtWidgets.QLabel(self.groupBox_device_info)
        self.label_device_ManufSer.setText("")
        self.label_device_ManufSer.setObjectName("label_device_ManufSer")
        self.gridLayout_2.addWidget(self.label_device_ManufSer, 8, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_device_info)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 10, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_device_info)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 8, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_device_info)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 6, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_device_info)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_device_MBver = QtWidgets.QLabel(self.groupBox_device_info)
        self.label_device_MBver.setText("")
        self.label_device_MBver.setObjectName("label_device_MBver")
        self.gridLayout_2.addWidget(self.label_device_MBver, 4, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_device_info)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_device_ModelName = QtWidgets.QLabel(self.groupBox_device_info)
        self.label_device_ModelName.setText("")
        self.label_device_ModelName.setObjectName("label_device_ModelName")
        self.gridLayout_2.addWidget(self.label_device_ModelName, 6, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_device_info)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 9, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_device_info)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 4, 0, 1, 1)
        self.label_device_DBver = QtWidgets.QLabel(self.groupBox_device_info)
        self.label_device_DBver.setText("")
        self.label_device_DBver.setObjectName("label_device_DBver")
        self.gridLayout_2.addWidget(self.label_device_DBver, 5, 1, 1, 1)
        self.label_device_SerialNumber = QtWidgets.QLabel(self.groupBox_device_info)
        self.label_device_SerialNumber.setText("")
        self.label_device_SerialNumber.setObjectName("label_device_SerialNumber")
        self.gridLayout_2.addWidget(self.label_device_SerialNumber, 7, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_device_info)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 7, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_device_info)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 5, 0, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_device_info, 0, 5, 3, 1)
        self.groupBox_sensors = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_sensors.setObjectName("groupBox_sensors")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_sensors)
        self.verticalLayout_8.setContentsMargins(-1, 6, -1, 6)
        self.verticalLayout_8.setSpacing(4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_34 = QtWidgets.QLabel(self.groupBox_sensors)
        self.label_34.setObjectName("label_34")
        self.gridLayout_9.addWidget(self.label_34, 4, 0, 1, 1)
        self.label_hdc_temp = QtWidgets.QLabel(self.groupBox_sensors)
        self.label_hdc_temp.setText("")
        self.label_hdc_temp.setObjectName("label_hdc_temp")
        self.gridLayout_9.addWidget(self.label_hdc_temp, 3, 1, 1, 1)
        self.label_grren_val = QtWidgets.QLabel(self.groupBox_sensors)
        self.label_grren_val.setText("")
        self.label_grren_val.setObjectName("label_grren_val")
        self.gridLayout_9.addWidget(self.label_grren_val, 5, 1, 1, 1)
        self.label_tiva_temp = QtWidgets.QLabel(self.groupBox_sensors)
        self.label_tiva_temp.setText("")
        self.label_tiva_temp.setObjectName("label_tiva_temp")
        self.gridLayout_9.addWidget(self.label_tiva_temp, 4, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.groupBox_sensors)
        self.label_33.setObjectName("label_33")
        self.gridLayout_9.addWidget(self.label_33, 3, 0, 1, 1)
        self.label_hum = QtWidgets.QLabel(self.groupBox_sensors)
        self.label_hum.setText("")
        self.label_hum.setObjectName("label_hum")
        self.gridLayout_9.addWidget(self.label_hum, 2, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.groupBox_sensors)
        self.label_32.setObjectName("label_32")
        self.gridLayout_9.addWidget(self.label_32, 2, 0, 1, 1)
        self.pushButton_readSensors = QtWidgets.QPushButton(self.groupBox_sensors)
        self.pushButton_readSensors.setObjectName("pushButton_readSensors")
        self.gridLayout_9.addWidget(self.pushButton_readSensors, 6, 0, 1, 2)
        self.label_batt_volt = QtWidgets.QLabel(self.groupBox_sensors)
        self.label_batt_volt.setText("")
        self.label_batt_volt.setObjectName("label_batt_volt")
        self.gridLayout_9.addWidget(self.label_batt_volt, 1, 1, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.groupBox_sensors)
        self.label_40.setObjectName("label_40")
        self.gridLayout_9.addWidget(self.label_40, 5, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_sensors)
        self.label_24.setObjectName("label_24")
        self.gridLayout_9.addWidget(self.label_24, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_sensors)
        self.label_4.setObjectName("label_4")
        self.gridLayout_9.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_batt_status = QtWidgets.QLabel(self.groupBox_sensors)
        self.label_batt_status.setText("")
        self.label_batt_status.setObjectName("label_batt_status")
        self.gridLayout_9.addWidget(self.label_batt_status, 0, 1, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_9)
        self.gridLayout_10.addWidget(self.groupBox_sensors, 2, 0, 2, 2)
        self.groupBox_lampusage = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_lampusage.setObjectName("groupBox_lampusage")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_lampusage)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_LampUsage_utl = QtWidgets.QLineEdit(self.groupBox_lampusage)
        self.lineEdit_LampUsage_utl.setObjectName("lineEdit_LampUsage_utl")
        self.gridLayout.addWidget(self.lineEdit_LampUsage_utl, 0, 0, 1, 2)
        self.pushButton_SetLampUsage = QtWidgets.QPushButton(self.groupBox_lampusage)
        self.pushButton_SetLampUsage.setObjectName("pushButton_SetLampUsage")
        self.gridLayout.addWidget(self.pushButton_SetLampUsage, 1, 0, 1, 1)
        self.pushButton_GetLampUsage = QtWidgets.QPushButton(self.groupBox_lampusage)
        self.pushButton_GetLampUsage.setObjectName("pushButton_GetLampUsage")
        self.gridLayout.addWidget(self.pushButton_GetLampUsage, 1, 1, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_lampusage, 1, 1, 1, 1)
        self.groupBox_dlpc = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_dlpc.setMinimumSize(QtCore.QSize(0, 148))
        self.groupBox_dlpc.setObjectName("groupBox_dlpc")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_dlpc)
        self.verticalLayout_6.setContentsMargins(-1, 6, -1, 6)
        self.verticalLayout_6.setSpacing(2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setVerticalSpacing(2)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.lineEdit_dlpc_fw_filename = QtWidgets.QLineEdit(self.groupBox_dlpc)
        self.lineEdit_dlpc_fw_filename.setMinimumSize(QtCore.QSize(240, 0))
        self.lineEdit_dlpc_fw_filename.setObjectName("lineEdit_dlpc_fw_filename")
        self.gridLayout_14.addWidget(self.lineEdit_dlpc_fw_filename, 0, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_dlpc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMinimumSize(QtCore.QSize(50, 0))
        self.label_17.setObjectName("label_17")
        self.gridLayout_14.addWidget(self.label_17, 0, 0, 1, 1)
        self.pushButton_dlpc_fw_update = QtWidgets.QPushButton(self.groupBox_dlpc)
        self.pushButton_dlpc_fw_update.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_dlpc_fw_update.sizePolicy().hasHeightForWidth())
        self.pushButton_dlpc_fw_update.setSizePolicy(sizePolicy)
        self.pushButton_dlpc_fw_update.setMinimumSize(QtCore.QSize(85, 0))
        self.pushButton_dlpc_fw_update.setObjectName("pushButton_dlpc_fw_update")
        self.gridLayout_14.addWidget(self.pushButton_dlpc_fw_update, 1, 2, 1, 1)
        self.pushButton_dlpc_fw_browse = QtWidgets.QPushButton(self.groupBox_dlpc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_dlpc_fw_browse.sizePolicy().hasHeightForWidth())
        self.pushButton_dlpc_fw_browse.setSizePolicy(sizePolicy)
        self.pushButton_dlpc_fw_browse.setMinimumSize(QtCore.QSize(85, 0))
        self.pushButton_dlpc_fw_browse.setObjectName("pushButton_dlpc_fw_browse")
        self.gridLayout_14.addWidget(self.pushButton_dlpc_fw_browse, 0, 2, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_14)
        self.gridLayout_10.addWidget(self.groupBox_dlpc, 4, 3, 1, 4)
        self.groupBox_TIVAFW = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_TIVAFW.setMinimumSize(QtCore.QSize(0, 148))
        self.groupBox_TIVAFW.setObjectName("groupBox_TIVAFW")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_TIVAFW)
        self.verticalLayout_5.setContentsMargins(-1, 6, -1, 6)
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setVerticalSpacing(2)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.pushButton_tiva_fw_usb_update = QtWidgets.QPushButton(self.groupBox_TIVAFW)
        self.pushButton_tiva_fw_usb_update.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_tiva_fw_usb_update.sizePolicy().hasHeightForWidth())
        self.pushButton_tiva_fw_usb_update.setSizePolicy(sizePolicy)
        self.pushButton_tiva_fw_usb_update.setMinimumSize(QtCore.QSize(85, 0))
        self.pushButton_tiva_fw_usb_update.setObjectName("pushButton_tiva_fw_usb_update")
        self.gridLayout_15.addWidget(self.pushButton_tiva_fw_usb_update, 1, 3, 1, 1)
        self.lineEdit_tiva_fw_filename = QtWidgets.QLineEdit(self.groupBox_TIVAFW)
        self.lineEdit_tiva_fw_filename.setMinimumSize(QtCore.QSize(240, 0))
        self.lineEdit_tiva_fw_filename.setObjectName("lineEdit_tiva_fw_filename")
        self.gridLayout_15.addWidget(self.lineEdit_tiva_fw_filename, 0, 1, 1, 2)
        self.pushButton_tiva_fw_browse = QtWidgets.QPushButton(self.groupBox_TIVAFW)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_tiva_fw_browse.sizePolicy().hasHeightForWidth())
        self.pushButton_tiva_fw_browse.setSizePolicy(sizePolicy)
        self.pushButton_tiva_fw_browse.setMinimumSize(QtCore.QSize(85, 0))
        self.pushButton_tiva_fw_browse.setObjectName("pushButton_tiva_fw_browse")
        self.gridLayout_15.addWidget(self.pushButton_tiva_fw_browse, 0, 3, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox_TIVAFW)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setMinimumSize(QtCore.QSize(50, 0))
        self.label_25.setObjectName("label_25")
        self.gridLayout_15.addWidget(self.label_25, 0, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_15)
        self.gridLayout_10.addWidget(self.groupBox_TIVAFW, 4, 0, 1, 3)
        self.groupBox_eeprom = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_eeprom.setObjectName("groupBox_eeprom")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_eeprom)
        self.gridLayout_4.setContentsMargins(-1, 6, -1, 6)
        self.gridLayout_4.setVerticalSpacing(4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_pix2wave_coeff2 = QtWidgets.QLabel(self.groupBox_eeprom)
        self.label_pix2wave_coeff2.setText("Pix-Wave Coeff 2")
        self.label_pix2wave_coeff2.setObjectName("label_pix2wave_coeff2")
        self.gridLayout_4.addWidget(self.label_pix2wave_coeff2, 2, 3, 1, 1)
        self.lineEdit_pix2wave1 = QtWidgets.QLineEdit(self.groupBox_eeprom)
        self.lineEdit_pix2wave1.setMaximumSize(QtCore.QSize(85, 16777215))
        self.lineEdit_pix2wave1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_pix2wave1.setObjectName("lineEdit_pix2wave1")
        self.gridLayout_4.addWidget(self.lineEdit_pix2wave1, 1, 5, 1, 1)
        self.lineEdit_shiftVect0 = QtWidgets.QLineEdit(self.groupBox_eeprom)
        self.lineEdit_shiftVect0.setMaximumSize(QtCore.QSize(85, 16777215))
        self.lineEdit_shiftVect0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_shiftVect0.setObjectName("lineEdit_shiftVect0")
        self.gridLayout_4.addWidget(self.lineEdit_shiftVect0, 3, 5, 1, 1)
        self.label_ref_cal_ver = QtWidgets.QLabel(self.groupBox_eeprom)
        self.label_ref_cal_ver.setObjectName("label_ref_cal_ver")
        self.gridLayout_4.addWidget(self.label_ref_cal_ver, 1, 1, 1, 1)
        self.label_scan_config_ver = QtWidgets.QLabel(self.groupBox_eeprom)
        self.label_scan_config_ver.setObjectName("label_scan_config_ver")
        self.gridLayout_4.addWidget(self.label_scan_config_ver, 2, 1, 1, 1)
        self.pushButton_eeprom_read = QtWidgets.QPushButton(self.groupBox_eeprom)
        self.pushButton_eeprom_read.setObjectName("pushButton_eeprom_read")
        self.gridLayout_4.addWidget(self.pushButton_eeprom_read, 7, 3, 1, 1)
        self.pushButton_eeprom_write = QtWidgets.QPushButton(self.groupBox_eeprom)
        self.pushButton_eeprom_write.setObjectName("pushButton_eeprom_write")
        self.gridLayout_4.addWidget(self.pushButton_eeprom_write, 7, 5, 1, 1)
        self.lineEdit_shiftVect1 = QtWidgets.QLineEdit(self.groupBox_eeprom)
        self.lineEdit_shiftVect1.setMaximumSize(QtCore.QSize(85, 16777215))
        self.lineEdit_shiftVect1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_shiftVect1.setObjectName("lineEdit_shiftVect1")
        self.gridLayout_4.addWidget(self.lineEdit_shiftVect1, 5, 5, 1, 1)
        self.label_ref_cal = QtWidgets.QLabel(self.groupBox_eeprom)
        self.label_ref_cal.setObjectName("label_ref_cal")
        self.gridLayout_4.addWidget(self.label_ref_cal, 1, 0, 1, 1)
        self.label_shiftVect_coeff0 = QtWidgets.QLabel(self.groupBox_eeprom)
        self.label_shiftVect_coeff0.setText("Shift Vect Coeff 0")
        self.label_shiftVect_coeff0.setObjectName("label_shiftVect_coeff0")
        self.gridLayout_4.addWidget(self.label_shiftVect_coeff0, 3, 3, 1, 1)
        self.label_pix2wave_coeff0 = QtWidgets.QLabel(self.groupBox_eeprom)
        self.label_pix2wave_coeff0.setText("Pix-Wave Coeff 0")
        self.label_pix2wave_coeff0.setObjectName("label_pix2wave_coeff0")
        self.gridLayout_4.addWidget(self.label_pix2wave_coeff0, 0, 3, 1, 1)
        self.lineEdit_shiftVect2 = QtWidgets.QLineEdit(self.groupBox_eeprom)
        self.lineEdit_shiftVect2.setMaximumSize(QtCore.QSize(85, 16777215))
        self.lineEdit_shiftVect2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_shiftVect2.setObjectName("lineEdit_shiftVect2")
        self.gridLayout_4.addWidget(self.lineEdit_shiftVect2, 6, 5, 1, 1)
        self.lineEdit_pix2wave0 = QtWidgets.QLineEdit(self.groupBox_eeprom)
        self.lineEdit_pix2wave0.setMaximumSize(QtCore.QSize(85, 16777215))
        self.lineEdit_pix2wave0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_pix2wave0.setText("")
        self.lineEdit_pix2wave0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_pix2wave0.setObjectName("lineEdit_pix2wave0")
        self.gridLayout_4.addWidget(self.lineEdit_pix2wave0, 0, 5, 1, 1)
        self.pushButton_eeprom_restore_default = QtWidgets.QPushButton(self.groupBox_eeprom)
        self.pushButton_eeprom_restore_default.setObjectName("pushButton_eeprom_restore_default")
        self.gridLayout_4.addWidget(self.pushButton_eeprom_restore_default, 7, 0, 1, 2)
        self.label_shiftVect_coeff1 = QtWidgets.QLabel(self.groupBox_eeprom)
        self.label_shiftVect_coeff1.setText("Shift Vect Coeff 1")
        self.label_shiftVect_coeff1.setObjectName("label_shiftVect_coeff1")
        self.gridLayout_4.addWidget(self.label_shiftVect_coeff1, 5, 3, 1, 1)
        self.lineEdit_pix2wave2 = QtWidgets.QLineEdit(self.groupBox_eeprom)
        self.lineEdit_pix2wave2.setMaximumSize(QtCore.QSize(85, 16777215))
        self.lineEdit_pix2wave2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_pix2wave2.setObjectName("lineEdit_pix2wave2")
        self.gridLayout_4.addWidget(self.lineEdit_pix2wave2, 2, 5, 1, 1)
        self.checkBox_eeprom_writeEN = QtWidgets.QCheckBox(self.groupBox_eeprom)
        self.checkBox_eeprom_writeEN.setObjectName("checkBox_eeprom_writeEN")
        self.gridLayout_4.addWidget(self.checkBox_eeprom_writeEN, 3, 0, 1, 2)
        self.label_scan_config = QtWidgets.QLabel(self.groupBox_eeprom)
        self.label_scan_config.setObjectName("label_scan_config")
        self.gridLayout_4.addWidget(self.label_scan_config, 2, 0, 1, 1)
        self.label_cal_coeff = QtWidgets.QLabel(self.groupBox_eeprom)
        self.label_cal_coeff.setObjectName("label_cal_coeff")
        self.gridLayout_4.addWidget(self.label_cal_coeff, 0, 0, 1, 1)
        self.label_shiftVect_coeff2 = QtWidgets.QLabel(self.groupBox_eeprom)
        self.label_shiftVect_coeff2.setText("Shift Vect Coeff 2")
        self.label_shiftVect_coeff2.setObjectName("label_shiftVect_coeff2")
        self.gridLayout_4.addWidget(self.label_shiftVect_coeff2, 6, 3, 1, 1)
        self.label_pix2wave_coeff1 = QtWidgets.QLabel(self.groupBox_eeprom)
        self.label_pix2wave_coeff1.setText("Pix-Wave Coeff 1")
        self.label_pix2wave_coeff1.setObjectName("label_pix2wave_coeff1")
        self.gridLayout_4.addWidget(self.label_pix2wave_coeff1, 1, 3, 1, 1)
        self.label_cal_coeff_ver = QtWidgets.QLabel(self.groupBox_eeprom)
        self.label_cal_coeff_ver.setObjectName("label_cal_coeff_ver")
        self.gridLayout_4.addWidget(self.label_cal_coeff_ver, 0, 1, 1, 1)
        self.pushButton_eeprom_write_generic = QtWidgets.QPushButton(self.groupBox_eeprom)
        self.pushButton_eeprom_write_generic.setObjectName("pushButton_eeprom_write_generic")
        self.gridLayout_4.addWidget(self.pushButton_eeprom_write_generic, 5, 0, 2, 3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 2, 4, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_eeprom, 2, 2, 2, 3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_8.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_8.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_keyActive = QtWidgets.QLabel(self.groupBox_2)
        self.label_keyActive.setObjectName("label_keyActive")
        self.gridLayout_8.addWidget(self.label_keyActive, 1, 1, 1, 1)
        self.pushButton_set_ActivationKey = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_set_ActivationKey.setObjectName("pushButton_set_ActivationKey")
        self.gridLayout_8.addWidget(self.pushButton_set_ActivationKey, 0, 2, 1, 1)
        self.pushButton_clear_ActivactionKey = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_clear_ActivactionKey.setObjectName("pushButton_clear_ActivactionKey")
        self.gridLayout_8.addWidget(self.pushButton_clear_ActivactionKey, 1, 2, 1, 1)
        self.lineEdit_key_number = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_key_number.setObjectName("lineEdit_key_number")
        self.gridLayout_8.addWidget(self.lineEdit_key_number, 0, 1, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_2, 3, 5, 1, 1)
        self.groupBox_Serial_Number_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_Serial_Number_2.setObjectName("groupBox_Serial_Number_2")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.groupBox_Serial_Number_2)
        self.gridLayout_22.setContentsMargins(-1, 6, -1, 6)
        self.gridLayout_22.setVerticalSpacing(4)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.lineEdit_SerNumber_utl = QtWidgets.QLineEdit(self.groupBox_Serial_Number_2)
        self.lineEdit_SerNumber_utl.setObjectName("lineEdit_SerNumber_utl")
        self.gridLayout_22.addWidget(self.lineEdit_SerNumber_utl, 0, 0, 1, 2)
        self.pushButton_SetSerNumber_utl = QtWidgets.QPushButton(self.groupBox_Serial_Number_2)
        self.pushButton_SetSerNumber_utl.setObjectName("pushButton_SetSerNumber_utl")
        self.gridLayout_22.addWidget(self.pushButton_SetSerNumber_utl, 1, 0, 1, 1)
        self.pushButton_GetSerNumber_utl = QtWidgets.QPushButton(self.groupBox_Serial_Number_2)
        self.pushButton_GetSerNumber_utl.setObjectName("pushButton_GetSerNumber_utl")
        self.gridLayout_22.addWidget(self.pushButton_GetSerNumber_utl, 1, 1, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_Serial_Number_2, 0, 1, 1, 1)
        self.groupBox_modelname = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_modelname.setObjectName("groupBox_modelname")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.groupBox_modelname)
        self.gridLayout_23.setContentsMargins(-1, 6, -1, 6)
        self.gridLayout_23.setVerticalSpacing(4)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.pushButton_GetModelName_utl = QtWidgets.QPushButton(self.groupBox_modelname)
        self.pushButton_GetModelName_utl.setObjectName("pushButton_GetModelName_utl")
        self.gridLayout_23.addWidget(self.pushButton_GetModelName_utl, 1, 1, 1, 1)
        self.pushButton_SetModelName_utl = QtWidgets.QPushButton(self.groupBox_modelname)
        self.pushButton_SetModelName_utl.setDefault(False)
        self.pushButton_SetModelName_utl.setObjectName("pushButton_SetModelName_utl")
        self.gridLayout_23.addWidget(self.pushButton_SetModelName_utl, 1, 0, 1, 1)
        self.lineEdit_ModelName_utl = QtWidgets.QLineEdit(self.groupBox_modelname)
        self.lineEdit_ModelName_utl.setObjectName("lineEdit_ModelName_utl")
        self.gridLayout_23.addWidget(self.lineEdit_ModelName_utl, 0, 0, 1, 2)
        self.gridLayout_10.addWidget(self.groupBox_modelname, 0, 0, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 650, 1061, 38))
        self.widget.setObjectName("widget")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_16.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_errStatus = QtWidgets.QLabel(self.widget)
        self.label_errStatus.setObjectName("label_errStatus")
        self.gridLayout_16.addWidget(self.label_errStatus, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_16.addWidget(self.label_6, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem5, 0, 2, 1, 1)
        self.pushButton_ResetErr = QtWidgets.QPushButton(self.widget)
        self.pushButton_ResetErr.setObjectName("pushButton_ResetErr")
        self.gridLayout_16.addWidget(self.pushButton_ResetErr, 0, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_ScanSetting.setCurrentIndex(0)
        self.comboBox_scanID.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Spectrum Plot"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Graph Controls"))
        self.radioButton_Intensity.setText(_translate("MainWindow", "Intensity"))
        self.radioButton_Absorbance.setText(_translate("MainWindow", "Absorbance"))
        self.radioButton_Reflectance.setText(_translate("MainWindow", "Reflectance"))
        self.radioButton_Reference.setText(_translate("MainWindow", "Reference"))
        self.groupBox_scan_controls_2.setTitle(_translate("MainWindow", "Scan Config Select"))
        self.pushButton_edit_scan_config_2.setText(_translate("MainWindow", "Modify"))
        self.label_scan_time_2.setText(_translate("MainWindow", "Total Scan Time (seconds)"))
        self.label_num_repeat_4.setText(_translate("MainWindow", "Num Scans to Average"))
        self.groupBox_ref_controls_2.setTitle(_translate("MainWindow", "Scan Reference Select"))
        self.radioButton_ref_factory.setText(_translate("MainWindow", "Factory Mode"))
        self.radioButton_ref_prev.setText(_translate("MainWindow", "Previous"))
        self.radioButton_ref_new.setText(_translate("MainWindow", "New"))
        self.groupBox_lampControl.setTitle(_translate("MainWindow", "Lamp Control"))
        self.lineEdit_lamp_stable_time.setText(_translate("MainWindow", "625"))
        self.radioButton_always_off.setText(_translate("MainWindow", "Keep Lamp OFF"))
        self.radioButton_always_on.setText(_translate("MainWindow", "Keep Lamp ON"))
        self.radioButton_Lamp_Stable_Time.setText(_translate("MainWindow", "Lamp Stable Time (Unit: ms, Default: 625)"))
        self.label_pga_gain_2.setText(_translate("MainWindow", "PGA Gain"))
        self.comboBox_pga_gain.setItemText(0, _translate("MainWindow", "Auto"))
        self.pushButton_scan.setText(_translate("MainWindow", "Scan"))
        self.checkBox_GlitchFilter.setText(_translate("MainWindow", "Enable Glitch Fliter"))
        self.checkBox_SaveBlackLevel.setText(_translate("MainWindow", "Save Black Level"))
        self.ckb_saveRawADC.setText(_translate("MainWindow", "Save Raw ADC"))
        self.label_connected.setText(_translate("MainWindow", "Not Connected!"))
        self.tabWidget_ScanSetting.setTabText(self.tabWidget_ScanSetting.indexOf(self.tab_6), _translate("MainWindow", "New Scan"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Scan"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Device & Reference"))
        self.pushButton_ResetSys.setText(_translate("MainWindow", "Reset"))
        self.label_35.setText(_translate("MainWindow", "Reset System"))
        self.label_31.setText(_translate("MainWindow", "Replace Reference Data"))
        self.pushButton_ReplaceRef.setText(_translate("MainWindow", "Update"))
        self.pushButton_ResotreRef.setText(_translate("MainWindow", "Restore"))
        self.label_2.setText(_translate("MainWindow", "Restore Factory Reference"))
        self.label.setText(_translate("MainWindow", "Back up Factory Reference"))
        self.pushButton_BackUpRef.setText(_translate("MainWindow", "Back up"))
        self.groupBox_datetime.setTitle(_translate("MainWindow", "Date and Time"))
        self.pushButton_GetDateTime.setText(_translate("MainWindow", "Get"))
        self.pushButton_SyncDateTime.setText(_translate("MainWindow", "Sync"))
        self.groupBox_device_info.setTitle(_translate("MainWindow", "Device Information"))
        self.label_9.setText(_translate("MainWindow", "Tiva SW Version"))
        self.label_7.setText(_translate("MainWindow", "Spectrum Library Ver."))
        self.label_16.setText(_translate("MainWindow", "Lamp Usage"))
        self.label_15.setText(_translate("MainWindow", "Manufacturing Ser."))
        self.label_13.setText(_translate("MainWindow", "Model Name"))
        self.label_10.setText(_translate("MainWindow", "GUI Version"))
        self.label_8.setText(_translate("MainWindow", "DLPC Flash Version"))
        self.label_18.setText(_translate("MainWindow", "Device UUID"))
        self.label_11.setText(_translate("MainWindow", "Main Board Ver."))
        self.label_14.setText(_translate("MainWindow", "Serial Number"))
        self.label_12.setText(_translate("MainWindow", "Detector Board Ver."))
        self.groupBox_sensors.setTitle(_translate("MainWindow", "Sensors"))
        self.label_34.setText(_translate("MainWindow", "Tiva Temp"))
        self.label_33.setText(_translate("MainWindow", "System Temp"))
        self.label_32.setText(_translate("MainWindow", "System Humidity"))
        self.pushButton_readSensors.setText(_translate("MainWindow", "Read"))
        self.label_40.setText(_translate("MainWindow", "Lamp Intensity"))
        self.label_24.setText(_translate("MainWindow", "Battery Capacity"))
        self.label_4.setText(_translate("MainWindow", "Battery Charger Status"))
        self.groupBox_lampusage.setTitle(_translate("MainWindow", "Lamp Usage"))
        self.pushButton_SetLampUsage.setText(_translate("MainWindow", "Set"))
        self.pushButton_GetLampUsage.setText(_translate("MainWindow", "Get"))
        self.groupBox_dlpc.setTitle(_translate("MainWindow", "DLPC150 Firmware Update"))
        self.label_17.setText(_translate("MainWindow", "File name"))
        self.pushButton_dlpc_fw_update.setText(_translate("MainWindow", "Update"))
        self.pushButton_dlpc_fw_browse.setText(_translate("MainWindow", "Browse"))
        self.groupBox_TIVAFW.setTitle(_translate("MainWindow", "TIVA Firmware Update"))
        self.pushButton_tiva_fw_usb_update.setText(_translate("MainWindow", "Update"))
        self.pushButton_tiva_fw_browse.setText(_translate("MainWindow", "Browse"))
        self.label_25.setText(_translate("MainWindow", "File name"))
        self.groupBox_eeprom.setTitle(_translate("MainWindow", "Calibration Coefficients"))
        self.label_ref_cal_ver.setText(_translate("MainWindow", "0"))
        self.label_scan_config_ver.setText(_translate("MainWindow", "0"))
        self.pushButton_eeprom_read.setText(_translate("MainWindow", "Read Coeff"))
        self.pushButton_eeprom_write.setText(_translate("MainWindow", "Write Coeff"))
        self.label_ref_cal.setText(_translate("MainWindow", "Ref Cal Ver:"))
        self.pushButton_eeprom_restore_default.setText(_translate("MainWindow", "Factory Default"))
        self.checkBox_eeprom_writeEN.setText(_translate("MainWindow", "Write Enable"))
        self.label_scan_config.setText(_translate("MainWindow", "Scan Conf Ver:"))
        self.label_cal_coeff.setText(_translate("MainWindow", "Cal Coeff Ver:"))
        self.label_cal_coeff_ver.setText(_translate("MainWindow", "0"))
        self.pushButton_eeprom_write_generic.setText(_translate("MainWindow", "Write Generic"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Activation Key"))
        self.label_5.setText(_translate("MainWindow", "Status"))
        self.label_3.setText(_translate("MainWindow", "Key"))
        self.label_keyActive.setText(_translate("MainWindow", "Actived!"))
        self.pushButton_set_ActivationKey.setText(_translate("MainWindow", "Set"))
        self.pushButton_clear_ActivactionKey.setText(_translate("MainWindow", "Clear"))
        self.groupBox_Serial_Number_2.setTitle(_translate("MainWindow", "Device Serial Number"))
        self.pushButton_SetSerNumber_utl.setText(_translate("MainWindow", "Set"))
        self.pushButton_GetSerNumber_utl.setText(_translate("MainWindow", "Get"))
        self.groupBox_modelname.setTitle(_translate("MainWindow", "Model Name"))
        self.pushButton_GetModelName_utl.setText(_translate("MainWindow", "Get"))
        self.pushButton_SetModelName_utl.setText(_translate("MainWindow", "Set"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Utility"))
        self.label_errStatus.setText(_translate("MainWindow", "one"))
        self.label_6.setText(_translate("MainWindow", "Error Status"))
        self.pushButton_ResetErr.setText(_translate("MainWindow", "Reset Err"))
