# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scanconfigdialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ScanConfigDialog(object):
    def setupUi(self, ScanConfigDialog):
        ScanConfigDialog.setObjectName("ScanConfigDialog")
        ScanConfigDialog.resize(846, 607)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ScanConfigDialog.sizePolicy().hasHeightForWidth())
        ScanConfigDialog.setSizePolicy(sizePolicy)
        ScanConfigDialog.setStyleSheet("")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(ScanConfigDialog)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_2 = QtWidgets.QLabel(ScanConfigDialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_8.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(188, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_add_config = QtWidgets.QPushButton(ScanConfigDialog)
        self.pushButton_add_config.setObjectName("pushButton_add_config")
        self.horizontalLayout_7.addWidget(self.pushButton_add_config)
        self.pushButton_edit_config = QtWidgets.QPushButton(ScanConfigDialog)
        self.pushButton_edit_config.setCheckable(True)
        self.pushButton_edit_config.setObjectName("pushButton_edit_config")
        self.horizontalLayout_7.addWidget(self.pushButton_edit_config)
        self.pushButton_delete_config = QtWidgets.QPushButton(ScanConfigDialog)
        self.pushButton_delete_config.setObjectName("pushButton_delete_config")
        self.horizontalLayout_7.addWidget(self.pushButton_delete_config)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.listWidget_target_scan_cfg = QtWidgets.QListWidget(ScanConfigDialog)
        self.listWidget_target_scan_cfg.setObjectName("listWidget_target_scan_cfg")
        self.verticalLayout_4.addWidget(self.listWidget_target_scan_cfg)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label = QtWidgets.QLabel(ScanConfigDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_14.addWidget(self.label)
        self.label_cfglist_activeCfg = QtWidgets.QLabel(ScanConfigDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_cfglist_activeCfg.sizePolicy().hasHeightForWidth())
        self.label_cfglist_activeCfg.setSizePolicy(sizePolicy)
        self.label_cfglist_activeCfg.setText("")
        self.label_cfglist_activeCfg.setObjectName("label_cfglist_activeCfg")
        self.horizontalLayout_14.addWidget(self.label_cfglist_activeCfg)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.pushButton_set_active = QtWidgets.QPushButton(ScanConfigDialog)
        self.pushButton_set_active.setObjectName("pushButton_set_active")
        self.verticalLayout_4.addWidget(self.pushButton_set_active)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_9.addLayout(self.horizontalLayout_5)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBox_3 = QtWidgets.QGroupBox(ScanConfigDialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout.addWidget(self.label_16)
        self.lineEdit_scan_config_name = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_scan_config_name.sizePolicy().hasHeightForWidth())
        self.lineEdit_scan_config_name.setSizePolicy(sizePolicy)
        self.lineEdit_scan_config_name.setMaxLength(13)
        self.lineEdit_scan_config_name.setObjectName("lineEdit_scan_config_name")
        self.horizontalLayout.addWidget(self.lineEdit_scan_config_name)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_2.addWidget(self.label_15)
        self.spinBox_num_scans_avg = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_num_scans_avg.setMinimum(1)
        self.spinBox_num_scans_avg.setMaximum(100)
        self.spinBox_num_scans_avg.setProperty("value", 1)
        self.spinBox_num_scans_avg.setObjectName("spinBox_num_scans_avg")
        self.horizontalLayout_2.addWidget(self.spinBox_num_scans_avg)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_NumSections = QtWidgets.QLabel(self.groupBox_3)
        self.label_NumSections.setObjectName("label_NumSections")
        self.horizontalLayout_3.addWidget(self.label_NumSections)
        self.spinBox_numSections = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_numSections.setMinimum(1)
        self.spinBox_numSections.setMaximum(5)
        self.spinBox_numSections.setObjectName("spinBox_numSections")
        self.horizontalLayout_3.addWidget(self.spinBox_numSections)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem1 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.SlewItemsWidget = QtWidgets.QTableWidget(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SlewItemsWidget.sizePolicy().hasHeightForWidth())
        self.SlewItemsWidget.setSizePolicy(sizePolicy)
        self.SlewItemsWidget.setMinimumSize(QtCore.QSize(700, 176))
        self.SlewItemsWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.SlewItemsWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.SlewItemsWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.SlewItemsWidget.setAutoScroll(False)
        self.SlewItemsWidget.setTabKeyNavigation(False)
        self.SlewItemsWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.SlewItemsWidget.setObjectName("SlewItemsWidget")
        self.SlewItemsWidget.setColumnCount(7)
        self.SlewItemsWidget.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        item.setText("1")
        self.SlewItemsWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("2")
        self.SlewItemsWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("3")
        self.SlewItemsWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("4")
        self.SlewItemsWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("5")
        self.SlewItemsWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.SlewItemsWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.SlewItemsWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.SlewItemsWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.SlewItemsWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.SlewItemsWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.SlewItemsWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.SlewItemsWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.SlewItemsWidget.setItem(0, 0, item)
        self.SlewItemsWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.SlewItemsWidget.horizontalHeader().setDefaultSectionSize(100)
        self.SlewItemsWidget.horizontalHeader().setHighlightSections(False)
        self.SlewItemsWidget.horizontalHeader().setMinimumSectionSize(25)
        self.SlewItemsWidget.horizontalHeader().setSortIndicatorShown(False)
        self.SlewItemsWidget.horizontalHeader().setStretchLastSection(False)
        self.SlewItemsWidget.verticalHeader().setVisible(False)
        self.SlewItemsWidget.verticalHeader().setHighlightSections(False)
        self.SlewItemsWidget.verticalHeader().setMinimumSectionSize(24)
        self.SlewItemsWidget.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout_11.addWidget(self.SlewItemsWidget)
        spacerItem2 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        spacerItem3 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.label_totalpatterns = QtWidgets.QLabel(self.groupBox_3)
        self.label_totalpatterns.setObjectName("label_totalpatterns")
        self.verticalLayout.addWidget(self.label_totalpatterns)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem4 = QtWidgets.QSpacerItem(178, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.pushButton_scan_config_save = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_scan_config_save.setMinimumSize(QtCore.QSize(20, 40))
        self.pushButton_scan_config_save.setObjectName("pushButton_scan_config_save")
        self.horizontalLayout_9.addWidget(self.pushButton_scan_config_save)
        spacerItem5 = QtWidgets.QSpacerItem(278, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.verticalLayout_7.addLayout(self.verticalLayout)
        self.label_wavelength_error = QtWidgets.QLabel(self.groupBox_3)
        self.label_wavelength_error.setText("")
        self.label_wavelength_error.setObjectName("label_wavelength_error")
        self.verticalLayout_7.addWidget(self.label_wavelength_error)
        self.verticalLayout_8.addWidget(self.groupBox_3)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem6 = QtWidgets.QSpacerItem(428, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem6)
        self.buttonBox = QtWidgets.QDialogButtonBox(ScanConfigDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_10.addWidget(self.buttonBox)
        self.verticalLayout_8.addLayout(self.horizontalLayout_10)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)

        self.retranslateUi(ScanConfigDialog)
        self.buttonBox.accepted.connect(ScanConfigDialog.accept)
        self.buttonBox.rejected.connect(ScanConfigDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ScanConfigDialog)

    def retranslateUi(self, ScanConfigDialog):
        _translate = QtCore.QCoreApplication.translate
        ScanConfigDialog.setWindowTitle(_translate("ScanConfigDialog", "Scan Configuration"))
        self.label_2.setText(_translate("ScanConfigDialog", "Scan Configs on Device"))
        self.pushButton_add_config.setText(_translate("ScanConfigDialog", "Add"))
        self.pushButton_edit_config.setText(_translate("ScanConfigDialog", "Edit"))
        self.pushButton_delete_config.setText(_translate("ScanConfigDialog", "Delete"))
        self.label.setText(_translate("ScanConfigDialog", "Current Active Config: "))
        self.pushButton_set_active.setToolTip(_translate("ScanConfigDialog", "Click to set the current selected Scan as default configuration on EVM"))
        self.pushButton_set_active.setText(_translate("ScanConfigDialog", "Set Active Config"))
        self.groupBox_3.setTitle(_translate("ScanConfigDialog", "Create/View/Edit  slew scan configuration"))
        self.label_16.setText(_translate("ScanConfigDialog", "Name"))
        self.label_15.setText(_translate("ScanConfigDialog", "No. of scans to average"))
        self.label_NumSections.setText(_translate("ScanConfigDialog", "No. of Sections "))
        item = self.SlewItemsWidget.horizontalHeaderItem(0)
        item.setText(_translate("ScanConfigDialog", "Method"))
        item = self.SlewItemsWidget.horizontalHeaderItem(1)
        item.setText(_translate("ScanConfigDialog", "Start nm"))
        item = self.SlewItemsWidget.horizontalHeaderItem(2)
        item.setText(_translate("ScanConfigDialog", "End nm"))
        item = self.SlewItemsWidget.horizontalHeaderItem(3)
        item.setText(_translate("ScanConfigDialog", "Width nm"))
        item = self.SlewItemsWidget.horizontalHeaderItem(4)
        item.setText(_translate("ScanConfigDialog", "Exposure ms"))
        item = self.SlewItemsWidget.horizontalHeaderItem(5)
        item.setText(_translate("ScanConfigDialog", "Dig Resolution"))
        item = self.SlewItemsWidget.horizontalHeaderItem(6)
        item.setText(_translate("ScanConfigDialog", "Pattern Range"))
        __sortingEnabled = self.SlewItemsWidget.isSortingEnabled()
        self.SlewItemsWidget.setSortingEnabled(False)
        self.SlewItemsWidget.setSortingEnabled(__sortingEnabled)
        self.label_totalpatterns.setText(_translate("ScanConfigDialog", "Patterns: "))
        self.pushButton_scan_config_save.setText(_translate("ScanConfigDialog", "Save Scan Configuration"))
